version: "3"

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "${DATABASE_PORT}:5432"
    volumes:
      - ./db-data/postgres:/var/lib/postgresql/data

  redis:
    image: "redis:alpine"
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - ./db-data/redis/:/data

  mailhog:
    image: "mailhog/mailhog:latest"
    ports:
      - "1025:1025"
      - "8025:8025"
    restart: always
